### ISSUE TITLE
Not Working Properly

### ISSUE THREAD

**Issue by Voltzen** [ApertureC/Fortnite-Music-Changer#1]
Hey, whenever I try to use this, it works for the first loading screen and after that stops working. Nothing for the main menu or lobby. And yes, I am using windowed fullscreen.

**Comment by ApertureC** [comment]
What's your resolution? Does it play the MP3 then stop, or is it just the normal fortnite loading music?

**Comment by ApertureC** [comment]
Try this and attach the log

[binaries-with-logging.zip](https://github.com/ApertureC/Fortnite-Music-Changer/files/2248608/binaries-with-logging.zip)

**Comment by Voltzen** [comment]
It plays the mp3 on the first loading screen then stops and my res is 1920x1080

**Comment by Voltzen** [comment]
Here is the log after use of the link
[log.txt](https://github.com/ApertureC/Fortnite-Music-Changer/files/2272649/log.txt)

**Comment by ApertureC** [comment]
Try the latest release since it fixed the other guys issue.
