### ISSUE TITLE
Party chat issue

### ISSUE THREAD

**Issue by XZCendence** [ApertureC/Fortnite-Music-Changer#10]
when I go to party chat and the text in the bottom left corner changer from "global" to "party", the music stops playing, also maybe when I look at an emote in the item shop, can you make the music quiet down as the game does, maybe by seeing if the text that tells what kind of item it is like "emote" next to the rarity could be used

**Comment by ApertureC** [comment]
Check "Play In Party", also I really don't want to do that anymore because I've abandoned the project, there are much better things I can do with my time because epic is going to put in the og music soon and make this entire thing useless.
