### ISSUE TITLE
is it possible to set the song to loop after its over?

### ISSUE THREAD

**Issue by AlgNinja** [ApertureC/Fortnite-Music-Changer#14]
right now after a 2 minute loop the music stops. is it possible to implement a loop system?

**Comment by ApertureC** [comment]
Definitely. It used to do that but I forgot to include it after moving audio stuff to a different file.

As a side note this is barely maintained as I don't really play fortnite anymore but I'll still fix issues if they're posted

**Comment by ApertureC** [comment]
I've released 4.3.1 which fixes this issue, you can download it here
https://github.com/ApertureC/Fortnite-Music-Changer/releases/latest
