### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by duellinksplayer210** [ApertureC/Fortnite-Music-Changer#16]
Hey I was thinking if it was possible to add music to a match, like when you're playing and there's some song playing, and if you're low on health it changes to another audio file of the users choice.

**Comment by ApertureC** [comment]
I'm 99% sure that playing music in a match is possible, however low health probably isn't. It'd rely on there being a log statement saying that the player is on low health (as well as they stop being on low health) - and I really doubt that, but I'll look into it.

**Comment by ApertureC** [comment]
Alright I've done some testing - low health isn't possible as it doesn't log anything to do with it, however music in match is possible and I'll add that for the next release

**Comment by ApertureC** [comment]
In game music has been added in the latest release
