### ISSUE TITLE
Plays lobby music even if Im not in the game

### ISSUE THREAD

**Issue by Aidenbax918** [ApertureC/Fortnite-Music-Changer#17]
As soon as I open the exe file it instantly plays the lobby music, it worked fine yesterday, but all the sudden it isn't working today. I don't have any other programs open when I open it and it still plays.

**Comment by ApertureC** [comment]
You can fix this by opening fortnite then closing it (~~or deleting the log file~~ - don't do this, there's a bug!)
 
What probably happened was that fortnite crashed and didn't finish the log file (the file needs to have a line with "Preparing to exit").

This should be a relatively easy fix as we just need to check if fortnite is open before playing anything.

**Comment by ApertureC** [comment]
Fixed. Will be apart of next release (today or tomorrow hopefully)
