### ISSUE TITLE
Program doesn't open.

### ISSUE THREAD

**Issue by blainsage** [ApertureC/Fortnite-Music-Changer#18]
Hello, I've previously used this back in season  CH2 S4 and it worked fine but now it doesn't seem to open. I have both the latest redistributables, and the 3.1.11 + 3.1.5 runtimes.

**Comment by ApertureC** [comment]
Just tested and it works here. Do you have at least .NET Framework 4.7.2 installed (installed by default in windows 10 1803)?

It's a bit strange that it magically stopped working, what might be happening is the config has completely screwed up somehow and is crashing when loading it. I'd recommend going to %localappdata% and delete Fortnite_Music_WPF to reset the settings.

**Comment by blainsage** [comment]
I'm running windows 10 pro v 19042.631 (i tweaked this version for gaming and just debloated it)
I do have the 4.7.2 framework as well
update: i see it start in my task manager and then maybe 2 seconds later it just closes

**Comment by ApertureC** [comment]
I just tested with a fresh copy of Windows and it's able to run (there is a bug with the selection of a different log file though - doesn't let you select it). So this may have to do with your installation. I can't think of anything that could cause it to crash except removing files from the download or a bad config...

Just to be super clear it doesn't open at all right? No dialogs saying that the log file couldn't be found?

**Comment by blainsage** [comment]
Nothing opens at all it just crashes i assume as it closes quick in task manager.
I have also tried deleting the folder in app data and it still didnt open

**Comment by ApertureC** [comment]
I'm sorry dude but if deleting the config file didn't work then I don't think I can fix it. You could try and build it from source & debug it though.

I think that you may have accidentally deleted an important file while debloating windows because it works on a fresh installation.

**Comment by blainsage** [comment]
Edit: it's all good now. - 
the issue was i didnt have windows media player as it was a part of the ps1 script i had to remove it

**Comment by ApertureC** [comment]
Cool, I'm glad it's working :)
