### ISSUE TITLE
Main menu music will play in-game in STW

### ISSUE THREAD

**Issue by Spueh** [ApertureC/Fortnite-Music-Changer#19]
I don't even know if this project is still alive anymore, but this issue is present.

**Comment by ApertureC** [comment]
I'm surprised anyone still uses this! I'll take a look at it later in the week.

**Comment by Spueh** [comment]
> I'm surprised anyone still uses this! I'll take a look at it later in the week.

Cool, will stay updated.

**Comment by ApertureC** [comment]
I've fixed the issue but I'd like to make a few more changes & do some testing before making a new release, so it'll probably be out tomorrow

**Comment by ApertureC** [comment]
Forgot to mention - the release is now available
