### ISSUE TITLE
issues with the app

### ISSUE THREAD

**Issue by imatrixgp** [ApertureC/Fortnite-Music-Changer#2]
It only works in the gamemode selection menu but then in the lobby of Battle Royale it does not play the music

**Comment by ApertureC** [comment]
What's your resolution?

**Comment by imatrixgp** [comment]
1920 x 1080 here is a log if u wanna see
[log.txt](https://github.com/ApertureC/Fortnite-Music-Changer/files/2250432/log.txt)

**Comment by ApertureC** [comment]
No idea why it's giving you a different colour - I'll probably make it a setup thing where it will automatically fill in the colour rather than base it off what it gives me.

**Comment by ApertureC** [comment]
Try the latest release, should fix the problem.

**Comment by imatrixgp** [comment]
Thank you now it works.

**Comment by ApertureC** [comment]
Alright then. Share this program around if you can, thanks!
