### ISSUE TITLE
Program won't open

### ISSUE THREAD

**Issue by ghost** [ApertureC/Fortnite-Music-Changer#21]
I don't know if the project is still alive and working for chapter 3 season 4 but i'll give it a shot since i really miss old fortnite lobby music and haven't got season x pass. The issue is pretty self explanatory and i tried using solutions for a similar issue but nothing worked. Please help

**Comment by ApertureC** [comment]
That's a bit odd, opens here. The issue you probably looked at (#18) was related to a debloating script. Are you definitely sure you haven't debloated windows or use windows modified/debloated by someone else? 

Also just to check, what windows version are you on?

**Comment by ghost** [comment]
Sorry for the late response. I did not use any script to delete any program in windows, but with some applications i managed to get edge uninstalled.
Btw my win version is win10 21H2 19044.2130

**Comment by ApertureC** [comment]
Sorry! I didn't get notified of your response for some reason, however since you've deleted your account I'm going to close this issue. I hope you've managed to fix it.
