### ISSUE TITLE
"Game end music" doesn't work in stw

### ISSUE THREAD

**Issue by kana5070** [ApertureC/Fortnite-Music-Changer#23]

**Comment by kana5070** [comment]
I mean when storm shield mission end, it doesn't play music.

**Comment by ApertureC** [comment]
I'll look into it tomorrow or the weekend, currently re-installing fortnite. It shouldn't be a difficult thing to fix provided it logs that it's ended.

**Comment by ApertureC** [comment]
I've fixed the issue and I've released a new version, you can download it here:

https://github.com/ApertureC/Fortnite-Music-Changer/releases/latest
