### ISSUE TITLE
lobby music when i click ready up button from the screen after dying

### ISSUE THREAD

**Issue by qwertyuiopaSDFGHJKLxagvuywnd** [ApertureC/Fortnite-Music-Changer#25]
![image](https://github.com/ApertureC/Fortnite-Music-Changer/assets/112568913/7869fbba-56f6-41bc-8931-d5512c73c7fb)
if i press this button the next game will use the lobby music, and also if you can is there a way to pause the music when emote music is playing? would help alot.

**Comment by ghost** [comment]
Still happens

**Comment by ApertureC** [comment]
Hi, unfortunately I am no longer maintaining fortnite music changer. I will archive the repository shortly to make it clear
