### ISSUE TITLE
frame drops

### ISSUE THREAD

**Issue by iphroid23** [ApertureC/Fortnite-Music-Changer#5]
My frames drop when this application is open.

**Comment by ApertureC** [comment]
Specs?
Windowed or Borderless?
Whats a normal framerate?
How much has it dropped?
Is it stutter?

**Comment by ApertureC** [comment]
My guess is that you're in fullscreen - which has a bad stutter
also a bug I found: changing resolution crashes the program

**Comment by liviiz** [comment]
How does the installation work there are 4 files how am i supposed to download it

**Comment by ApertureC** [comment]
Extract the zip and then run the setup.exe from here https://github.com/ApertureC/Fortnite-Music-Changer/releases/latest (download binaries-installer)

**Comment by ApertureC** [comment]
no idea how to fix it properly, I've made a change that makes it slightly more bearable, but it takes ~3 seconds for the menu music to start

**Comment by liviiz** [comment]
whats the point of the other 3 files then?

**Comment by liviiz** [comment]
theres 4 in total isnt there

**Comment by ApertureC** [comment]
Try the latest release

**Comment by ApertureC** [comment]
oH fUcK FNBRLeaks has found the latest version :(
