### ISSUE TITLE
The program eats fps...

### ISSUE THREAD

**Issue by Yoruiopz** [ApertureC/Fortnite-Music-Changer#7]
Without this running, my fps goes to 140 in game on all epic.
when I have this running my game drops to 50 fps occasionally.
I run on a gtx 1080 and an i7 7700k 16gb ram
this is a big impact to performance since I run on a 75hz monitor too.

**Comment by ssgzer0ne** [comment]
It's only you have such problems, I have everything ok

**Comment by Yoruiopz** [comment]
@ssgzer0ne Its not only me, so it is for all of my 5 friends.

**Comment by ApertureC** [comment]
Hey I'm working on a fix.
My advice: Don't use it right now.

**Comment by ApertureC** [comment]
got a fix

**Comment by ApertureC** [comment]
Add me on discord I need you to test it: Aperture#6237

**Comment by ApertureC** [comment]
Fixed with latest release
