### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by Scavenger221** [ApertureC/Fortnite-Music-Changer#8]
hey i really dont understand how to use it should i put in the game files or what please help.

**Comment by ApertureC** [comment]
I'll make a tutorial soon-ish (depends when I can get the performance to improve)

**Comment by innowebka** [comment]
tutorial plz? how to ?

**Comment by ApertureC** [comment]
https://github.com/ApertureC/Fortnite-Music-Changer/releases/latest

go to "DOWNLOAD-THIS.zip" and open it and extract it. Then run Fortnite Music WPF.exe and click "browse" on each of the sections and put in your music.

**Comment by Scavenger221** [comment]
Thx for answering after almost a year and a half lol

**Comment by ApertureC** [comment]
lol I guess I forgot about it and closed it... was dealing with FNBRLeaks taking this at the time so I was kind of busy. @innowebka asked for help on this issue (despite it being dead old), didn't think about it pinging you, sorry!

**Comment by Scavenger221** [comment]
No your totally good bro its fine
